apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  labels:
    run: odoo-service
  namespace: odoo
spec:
  type: LoadBalancer
  ports:
  - port: 8069
    protocol: TCP
  selector:
    app: odoo